### ISSUE TITLE
deployment to nginx centos

### ISSUE THREAD

**Issue by rkang30** [webtutsplus/videoChat-WebFrontend#2]
Hi Shivam,

Thank you so much for sharing a cool video chat app. I got it working on my centos server by running it on the port 8000. But is there any way that I can host this without port? (Currently it's running on example.com:8000/videoChat.)

I was trying to load the video chat app on my website "example.com/videoChat" by using https reverse proxy but had no luck.

Could you show me how to deploy it on https domain without port? 

Thanks in advance!
Ryan

**Comment by shivamag00** [comment]
Hi @rkang30 . When we enter a url containing `http://` in our browser's URL bar, it automatically makes a request to the port 80. Similarly, if we enter a url containing `https://` in our browser's URL bar, it automatically makes a request to the port 443.

There are two solutions for your problem:-

1. If you host the application on port 80, you will be able to run the application with the URL http://example.com/videoChat. Similarly, use port 443 for https. For https, you will need an SSL certificate which you can generate for free using Let's Encrypt Certbot. 
2. Other option is that you use port forwarding - you can forward port 80 to 8000 so that any requests to port 80 will be handled by port 8000. Similarly, you can forward port 443 to 8000

I hope this solves your query. Let us know if you any doubt.

**Comment by rkang30** [comment]
Thank you so much @shivamag00 !
